### ISSUE TITLE
Cubo

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#4]
Creare un programma cubo.py che chieda all'utente
il lato di un cubo (intero) e ne stampi il volume

**Comment by LuigiVessella** [comment]
error: failed to push some refs to 'https://github.com/LuigiVessella/helloworld'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Perchè non mi carica cubo.py?

**Comment by FabioZTessitore** [comment]
confessa ... il file lo hai cancellato direttamente dal sito?
Ogni volta che la repo remota cambia devi sincronizzare quella locale con un pull

**Comment by LuigiVessella** [comment]
Ahh, quindi se cancello un qualsiasi file o lo modifico dal sito, quello influisce anche sui file a cui lavoro se non sincronizzo?
Confesso...

**Comment by LuigiVessella** [comment]
Ma ora mi apre GNU NANO e non mi fa fare nulla

**Comment by FabioZTessitore** [comment]
ti sei incartato, cancella la cartella e rifai il clone

**Comment by LuigiVessella** [comment]
Fatto!
